# Generated by Django 5.1.5 on 2025-05-02 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.CharField(db_index=True, max_length=100)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("description", models.CharField(max_length=200)),
                ("last_fetched", models.DateTimeField(default=django.utils.timezone.now)),
                ("forecast_date", models.DateField(db_index=True, default=django.utils.timezone.now)),
                ("zip_code", models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [models.Index(fields=["location", "last_fetched"], name="weather_wea_locatio_ed4383_idx")],
                "unique_together": {("zip_code", "location", "forecast_date")},
            },
        ),
    ]
