# Generated by Django 5.1.5 on 2025-05-03 01:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherForecastDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("condition_text", models.TextField(max_length=20, verbose_name="Condition")),
                ("condition_icon_url", models.TextField(max_length=255, verbose_name="Icon URL")),
                ("condition_code", models.IntegerField()),
                ("last_fetched", models.DateTimeField(default=django.utils.timezone.now)),
                ("forecast_date", models.DateField(db_index=True, default=django.utils.timezone.now)),
                ("zip_code", models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ("createdatetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("location", models.CharField(db_index=True, max_length=100)),
                ("maxtemp_c", models.FloatField()),
                ("maxtemp_f", models.FloatField()),
                ("mintemp_c", models.FloatField()),
                ("mintemp_f", models.FloatField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherForecastHour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("condition_text", models.TextField(max_length=20, verbose_name="Condition")),
                ("condition_icon_url", models.TextField(max_length=255, verbose_name="Icon URL")),
                ("condition_code", models.IntegerField()),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("teperature_f", models.FloatField()),
                ("teperature_c", models.FloatField()),
                ("wind_mph", models.IntegerField()),
                ("wind_kph", models.IntegerField()),
                ("wind_direction", models.TextField(max_length=3, verbose_name="Wind Direction")),
                ("wind_heading", models.IntegerField(verbose_name="Wind Heading")),
                ("feelslike_c", models.FloatField()),
                ("feelslike_f", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
        migrations.AddIndex(
            model_name="weatherforecastday",
            index=models.Index(fields=["last_fetched"], name="weather_wea_last_fe_ef77a4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="weatherforecastday",
            unique_together={("zip_code", "forecast_date")},
        ),
        migrations.AddField(
            model_name="weatherforecasthour",
            name="forecast",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="weather.weatherforecastday"),
        ),
        migrations.AddIndex(
            model_name="weatherforecasthour",
            index=models.Index(fields=["time"], name="weather_wea_time_80c2f7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="weatherforecasthour",
            unique_together={("forecast", "time")},
        ),
    ]
