# Generated by Django 5.1.5 on 2025-05-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_weatherforecastday_weatherforecasthour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherforecastday",
            name="condition_icon_url",
            field=models.CharField(max_length=255, verbose_name="Icon URL"),
        ),
        migrations.AlterField(
            model_name="weatherforecastday",
            name="condition_text",
            field=models.CharField(max_length=20, verbose_name="Condition"),
        ),
        migrations.AlterField(
            model_name="weatherforecasthour",
            name="condition_icon_url",
            field=models.CharField(max_length=255, verbose_name="Icon URL"),
        ),
        migrations.AlterField(
            model_name="weatherforecasthour",
            name="condition_text",
            field=models.CharField(max_length=20, verbose_name="Condition"),
        ),
    ]
