# Generated by Django 5.1.5 on 2025-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_alter_weatherforecastday_condition_icon_url_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherforecastday",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="weatherforecasthour",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="weatherforecastday",
            constraint=models.UniqueConstraint(fields=("zip_code", "forecast_date"), name="unique_zip_forecastdate"),
        ),
        migrations.AddConstraint(
            model_name="weatherforecasthour",
            constraint=models.UniqueConstraint(fields=("forecast", "time"), name="unique_forecast_time"),
        ),
    ]
