# Generated by Django 5.1.5 on 2025-05-05 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_alter_weatherforecastday_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherforecastday",
            name="location",
        ),
    ]
