# Generated by Django 5.1.5 on 2025-05-05 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0005_remove_weatherforecastday_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherforecasthour",
            old_name="teperature_c",
            new_name="temperature_c",
        ),
        migrations.RenameField(
            model_name="weatherforecasthour",
            old_name="teperature_f",
            new_name="temperature_f",
        ),
    ]
