# Generated by Django 5.1.5 on 2025-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0006_rename_teperature_c_weatherforecasthour_temperature_c_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherforecastday",
            name="condition_text",
            field=models.CharField(max_length=100, verbose_name="Condition"),
        ),
        migrations.AlterField(
            model_name="weatherforecasthour",
            name="condition_text",
            field=models.CharField(max_length=100, verbose_name="Condition"),
        ),
    ]
