# Generated by Django 5.1.5 on 2025-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0007_alter_weatherforecastday_condition_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherforecastday",
            name="condition_text",
            field=models.CharField(max_length=60, verbose_name="Condition"),
        ),
        migrations.AlterField(
            model_name="weatherforecasthour",
            name="condition_text",
            field=models.CharField(max_length=60, verbose_name="Condition"),
        ),
    ]
