# Generated by Django 5.1.5 on 2025-05-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0008_alter_weatherforecastday_condition_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherforecastday",
            name="maxwind_kph",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherforecastday",
            name="maxwind_mph",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
