# Generated by Django 5.1.5 on 2025-05-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0009_weatherforecastday_maxwind_kph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherforecasthour",
            name="hour",
            field=models.SmallIntegerField(default=0),
        ),
    ]
