# Generated by Django 5.1.5 on 2025-05-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0010_weatherforecasthour_hour"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="weatherforecasthour",
            name="unique_forecast_time",
        ),
        migrations.RemoveIndex(
            model_name="weatherforecasthour",
            name="weather_wea_time_80c2f7_idx",
        ),
        migrations.RemoveField(
            model_name="weatherforecasthour",
            name="time",
        ),
        migrations.AddIndex(
            model_name="weatherforecasthour",
            index=models.Index(fields=["hour"], name="weather_wea_hour_28c36d_idx"),
        ),
        migrations.AddConstraint(
            model_name="weatherforecasthour",
            constraint=models.UniqueConstraint(fields=("forecast", "hour"), name="unique_forecast_time"),
        ),
    ]
