# Generated by Django 5.1.5 on 2025-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0011_remove_weatherforecasthour_unique_forecast_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherforecasthour",
            name="chance_of_rain",
            field=models.IntegerField(default=0, verbose_name="Rain Chance"),
        ),
        migrations.AddField(
            model_name="weatherforecasthour",
            name="chance_of_snow",
            field=models.IntegerField(default=0, verbose_name="Snow Chance"),
        ),
    ]
