# Generated by Django 5.1.5 on 2025-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0012_weatherforecasthour_chance_of_rain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherforecastday",
            name="chance_of_rain",
            field=models.IntegerField(default=0, verbose_name="Rain Chance"),
        ),
        migrations.AddField(
            model_name="weatherforecastday",
            name="chance_of_snow",
            field=models.IntegerField(default=0, verbose_name="Snow Chance"),
        ),
    ]
