# Generated by Django 4.2.13 on 2024-05-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavBarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "template_name",
                    models.CharField(max_length=50, verbose_name="Template Name"),
                ),
                ("order", models.IntegerField(verbose_name="Sort Order")),
                ("active", models.BooleanField(verbose_name="Active")),
            ],
        ),
        migrations.CreateModel(
            name="ZipCodeCoordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.TextField(verbose_name="Zip Code")),
                ("lat", models.DecimalField(decimal_places=5, max_digits=8)),
                ("long", models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["zip_code"], name="data_zipcod_zip_cod_44278d_idx"
                    )
                ],
            },
        ),
    ]
