# Generated by Django 5.1.5 on 2025-05-12 21:25

import group_velo.data.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0023_alter_route_start_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="start_zip_code",
            field=models.CharField(
                default=12345,
                max_length=5,
                validators=[group_velo.data.validators.numeric_chars, group_velo.data.validators.length_of_five],
                verbose_name="Zip Code",
            ),
            preserve_default=False,
        ),
    ]
