from django.contrib.auth.decorators import login_required
from django.urls import include, path

from group_velo.events.decorators import can_view_user_emergency_contacts, user_is_ride_leader, user_is_ride_member

from . import views

app_name = "events"

urlpatterns = [
    path("", views.AvailableRidesView.as_view(), name="available_rides"),
    path("save_filter/", views.save_filter, name="save_filter"),
    path(
        "get_promote_demote_rider_disabled_button/",
        views.get_promote_demote_rider_disabled_button,
        name="get_promote_demote_rider_disabled_button",
    ),
    path(
        "get_blank_cancel_event_form/",
        views.get_blank_cancel_event_form,
        name="get_blank_cancel_event_form",
    ),
    path(
        "get_blank_cancel_event_occurence_form",
        views.get_blank_cancel_event_occurence_form,
        name="get_blank_cancel_event_occurence_form",
    ),
    path(
        "delete_filter/<str:saved_filter_sqid>/",
        views.delete_filter,
        name="delete_filter",
    ),
    path(
        "event_occurences/<str:event_sqid>/",
        views.get_cancel_event_form,
        name="get_cancel_event_form",
    ),
    path("registered/", views.MyRidesView.as_view(), name="my_rides"),
    path("waitlist/", views.MyWaitlistView.as_view(), name="my_waitlist"),
    path(
        "ride_classification_limits/",
        views.get_ride_classification_limits,
        name="get_ride_classification_limits",
    ),
    path(
        "get_blank_leave_list_form/",
        views.get_blank_leave_list_form,
        name="get_blank_leave_list_form",
    ),
    # Ride Registration
    path(
        "registration/<str:event_occurence_sqid>/",
        include(
            [
                path(
                    "get_leave_ride_form/",
                    views.get_leave_ride_form,
                    name="get_leave_ride_form",
                ),
                path(
                    "get_leave_waitlist_form/",
                    views.get_leave_waitlist_form,
                    name="get_leave_waitlist_form",
                ),
                path(
                    "get_join_ride_form/",
                    views.get_join_ride_form,
                    name="get_join_ride_form",
                ),
                path(
                    "get_join_waitlist_form/",
                    views.get_join_waitlist_form,
                    name="get_join_waitlist_form",
                ),
                path(
                    "get_cancel_event_occurence_form",
                    views.get_cancel_event_occurence_form,
                    name="get_cancel_event_occurence_form",
                ),
                path(
                    "delete/",
                    include(
                        [
                            path(
                                "",
                                views.DeleteRideRegistrationView.as_view(),
                                name="delete_registration",
                            ),
                            path(
                                "waitlist/",
                                include(
                                    [
                                        path(
                                            "",
                                            views.DeleteRideWaitlistRegistrationView.as_view(),
                                            name="delete_waitlist_registration",
                                        ),
                                        path(
                                            "<str:rider_sqid>/",
                                            views.LeaderDeleteRideWaitlistRegistrationView.as_view(),
                                            name="leader_delete_ride_waitlist_registration",
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
                path(
                    "create/",
                    include(
                        [
                            path(
                                "",
                                views.CreateRideRegistrationView.as_view(),
                                name="create_registration",
                            ),
                            path(
                                "waitlist/",
                                views.CreateWaitlistRegistrationView.as_view(),
                                name="create_waitlist_registration",
                            ),
                        ]
                    ),
                ),
                path(
                    "ride_leader/<str:rider_sqid>/",
                    include(
                        [
                            path(
                                "promote/",
                                include(
                                    [
                                        path(
                                            "",
                                            views.PromoteToRideLeaderView.as_view(),
                                            name="promote_to_ride_leader",
                                        ),
                                        path(
                                            "get_form/",
                                            views.get_promote_rider_form,
                                            name="get_promote_rider_form",
                                        ),
                                    ]
                                ),
                            ),
                            path(
                                "demote/",
                                include(
                                    [
                                        path(
                                            "",
                                            views.DemoteFromRideLeader.as_view(),
                                            name="demote_from_ride_leader",
                                        ),
                                        path(
                                            "get_form/",
                                            views.get_demote_rider_form,
                                            name="get_demote_rider_form",
                                        ),
                                    ]
                                ),
                            ),
                            path(
                                "delete/",
                                include(
                                    [
                                        path(
                                            "",
                                            views.LeaderDeleteRideRegistrationView.as_view(),
                                            name="leader_delete_ride_registration",
                                        ),
                                        path(
                                            "get_form/",
                                            views.get_kick_rider_form,
                                            name="get_kick_rider_form",
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                    name="ride_leader",
                ),
            ]
        ),
    ),
    # Event Create
    path(
        "create/",
        login_required(views.CreateEvent.as_view(), login_url="/login"),
        name="create_event",
    ),
    # Event Delete
    path(
        "delete_event/<str:event_sqid>/",
        views.DeleteEventView.as_view(),
        name="delete_event",
    ),
    path(
        "<str:event_occurence_sqid>/",
        include(
            [
                path(
                    "delete/",
                    views.DeleteEventOccurenceView.as_view(),
                    name="delete_event_occurence",
                ),
                path(
                    "edit/<str:slug>/",
                    (
                        login_required(
                            user_is_ride_leader(views.ModifyEvent.as_view()),
                            login_url="/login",
                        )
                    ),
                    name="modify_event",
                ),
                path(
                    "comments/",
                    include(
                        [
                            path(
                                "",
                                login_required(
                                    user_is_ride_member(views.EventComments.as_view()),
                                    login_url="/login",
                                ),
                                name="ride_comments",
                            ),
                            path(
                                "click/",
                                views.EventOccurenceCommentClickView.as_view(),
                                name="ride_comments_click",
                            ),
                        ]
                    ),
                ),
                path(
                    "attendees/",
                    include(
                        [
                            path(
                                "",
                                views.RideAttendeesView.as_view(),
                                name="ride_attendees",
                            ),
                            path(
                                "waitlist/",
                                views.RideWaitlistView.as_view(),
                                name="ride_waitlist",
                            ),
                        ]
                    ),
                ),
                path(
                    "emergency_contacts/<str:user_sqid>/",
                    login_required(
                        can_view_user_emergency_contacts(views.user_emergency_contacts),
                        login_url="/login",
                    ),
                    name="user_emergency_contacts",
                ),
            ]
        ),
    ),
]
