# Generated by Django 4.2.13 on 2024-05-17 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (0, "Ride Modified"),
                            (1, "Ride Canceled"),
                            (2, "Waitlist Promotion"),
                            (3, "Ride Registration Canceled"),
                            (4, "Waitlist Registration Deleted"),
                        ],
                        verbose_name="Notification Type",
                    ),
                ),
                ("opened", models.BooleanField(default=False, verbose_name="Opened")),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                ("subject", models.TextField(verbose_name="Subject")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "custom_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Custom Message"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Date"),
                ),
                (
                    "event_occurence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventoccurence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="notificatio_user_id_c291d5_idx")
                ],
            },
        ),
    ]
