# Generated by Django 5.1.5 on 2025-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="eventoccurence",
            name="description",
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name="Description"),
        ),
    ]
