# Generated by Django 5.1.5 on 2025-05-02 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0004_alter_club_state"),
        ("events", "0002_event_description_eventoccurence_description"),
        ("routes", "0004_alter_route_start_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventoccurence",
            name="start_zip_code",
            field=models.CharField(default=75072, max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="eventoccurence",
            index=models.Index(fields=["ride_date", "start_zip_code"], name="events_even_ride_da_a96daa_idx"),
        ),
    ]
