# Generated by Django 5.1.5 on 2025-05-12 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0020_alter_club_state"),
        ("events", "0003_eventoccurence_start_zip_code_and_more"),
        ("routes", "0024_alter_route_start_zip_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="eventoccurence",
            name="events_even_ride_da_a96daa_idx",
        ),
        migrations.RemoveField(
            model_name="eventoccurence",
            name="start_zip_code",
        ),
        migrations.AddIndex(
            model_name="eventoccurence",
            index=models.Index(fields=["ride_date"], name="events_even_ride_da_acc9a6_idx"),
        ),
    ]
